it ('Register as a new user', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('069999999')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.url().should('eq', 'https://practicesoftwaretesting.com/#/auth/login')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="login-submit"]').click()
    cy.url().should('eq', 'https://practicesoftwaretesting.com/#/account')

})

it ('Register as a new user - wrong email format', function () {
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('069999999')
    cy.get('[data-test="email"]').type('test')
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="email-error"] > div').should('be.visible')
    cy.get('[data-test="email-error"] > div').contains('E-mail format is invalid.')  
   })

   it ('Register as a new user - wrong phone format', function () {
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('dfadsfdasf')
    cy.get('[data-test="email"]').type('test@test.com')
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="phone-error"] > div').should('be.visible')
    cy.get('[data-test="phone-error"] > div').contains(' Only numbers are allowed.')  
   })

   it ('Register as a new user - wrong phone and email format', function () {
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('dfadsfdasf')
    cy.get('[data-test="email"]').type('test')
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="phone-error"] > div').should('be.visible')
    cy.get('[data-test="phone-error"] > div').contains(' Only numbers are allowed.')  
    cy.get('[data-test="email-error"] > div').should('be.visible')
    cy.get('[data-test="email-error"] > div').contains('E-mail format is invalid.')  
   })

it ('Register as a new user - First name required field not filled', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('069999999')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="first-name-error"] > div').should('be.visible')
    cy.get('[data-test="first-name-error"] > div').contains('First name is required.')
   })

it ('Register as a new user - Last name required field not filled', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('069999999')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="last-name-error"] > div').should('be.visible')
    cy.get('[data-test="last-name-error"] > div').contains('Last name is required.')
   })

   it ('Register as a new user - Date of birth required field not filled', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('069999999')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="dob-error"] > div').should('be.visible')
    cy.get('[data-test="dob-error"] > div').contains('Date of Birth is required.')
   })

   it ('Register as a new user - Date of birth required field not filled', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('069999999')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="postcode-error"] > div').should('be.visible')
    cy.get('[data-test="postcode-error"] > div').contains('Postcode is required.')
   })

   it ('Register as a new user - Address required field not filled', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('069999999')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="address-error"] > div').should('be.visible')
    cy.get('[data-test="address-error"] > div').contains('Address is required.')
   })
  

   it ('Register as a new user - City required field not filled', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('069999999')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="city-error"] > div').should('be.visible')
    cy.get('[data-test="city-error"] > div').contains('City is required.')
   })

   it ('Register as a new user - State required field not filled', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('069999999')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="state-error"] > div').should('be.visible')
    cy.get('[data-test="state-error"] > div').contains('State is required.')
   })

   it ('Register as a new user - Country required field not filled', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="phone"]').type('069999999')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="country-error"] > div').should('be.visible')
    cy.get('[data-test="country-error"] > div').contains('Country is required.')
   })

   it ('Register as a new user - Phone required field not filled', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="phone-error"] > div').should('be.visible')
    cy.get('[data-test="phone-error"] > div').contains('Phone is required.')
   })

   it ('Register as a new user - Email required field not filled', function () {
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('060000000')
    cy.get('[data-test="password"]').type('password')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="email-error"] > div').should('be.visible')
    cy.get('[data-test="email-error"] > div').contains('E-mail is required.')
   })

   it ('Register as a new user - Password required field not filled', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('060000000')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="password-error"] > div').should('be.visible')
    cy.get('[data-test="password-error"] > div').contains('Password is required.')
   })

   it ('Register as a new user - Password too short', function () {
    var user = `${Date.now()}@test.com`
    cy.visit('https://practicesoftwaretesting.com/#/')
    cy.get('[data-test="nav-sign-in"]').click()
    cy.get('[data-test="register-link"]').click()
    cy.get('[data-test="first-name"]').type('Dragana')
    cy.get('[data-test="last-name"]').type('Vlajnic')
    cy.get('[data-test="dob"]').type('1991-12-31')
    cy.get('[data-test="address"]').type('Ulica 1/1')
    cy.get('[data-test="postcode"]').type('11000')
    cy.get('[data-test="city"]').type('Belgrade')
    cy.get('[data-test="state"]').type('Serbia')
    cy.get('[data-test="country"]').select("Serbia")
    cy.get('[data-test="phone"]').type('060000000')
    cy.get('[data-test="email"]').type(user)
    cy.get('[data-test="password"]').type('aaa')
    cy.get('[data-test="register-submit"]').click()
    cy.get('[data-test="password-error"] > div').should('be.visible')
    cy.get('[data-test="password-error"] > div').contains('Password must be minimal 6 characters long.')
   })